### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by hanrastic** [sonjamadetoja/RSA-salaus#1]
### Kommentteja
- Koodi on jaettu järkevästi luokkiin ja funktiot ovat järkeviä. Yleinen rakenne on selkeä.
- Koodi on hyvin ja selkeästi kommentoitua. Koodia on helppo ja mukava lukea.
- Koodissa on tiettyjä kohtia avainten luonnista joista en saa selvää, mutta se lienee ohtuu enemmänkin katselmoijan matemaattisesta osaamisesta.
- Ohjelma kaatuu useassa tilanteessa virheellisellä syötteellä. Esim kun antaa kirjaimia kun halutaan numeroita ja toisinpäin.
- Testaus on kattavaa ja testit järkeviä
- Käytettävyys kärsii, kun pitää kopioida avaimia salatessa ja purkaessa.

### Mahdollisia kehitysehdotuksia
- Valitsemalla (3) ja antamalla keksityn viestin ohjelma kaatuu.
- Viestiä salatessa modulus-osa ja julkinen osa voisi tayttyä automaattisesti. Ainakin modulus osa turhan pitkä kopioitavaksi. Ellei toki tässä takana ole joku ajatus mikä ei minulle selvinnyt. 
- Testauksen ajamisen ohjeeseen voisi lisätä että täytyy ensin ladata riippuvuudet (poetry install)

**Comment by sonjamadetoja** [comment]
Kiitos kommenteistasi! Olen pahoillani, että en ehtinyt kirjoittaa käyttöohjeita ennen katselmointia! Se olisi varmasti helpottanut testaamista. 

Millaisella viestillä ohjelma kaatui? 2048-bittisellä salausavaimella (jonka ohjelma tässä luo) voi salata korkeintaan 256 bitin pituisia viestejä, joten sitä suuremmilla viesteillä ohjelma kaatuu, kun en ole vielä ehtinyt huomioda tätä käyttäliittymässä, mutta jos viestisi oli lyhyempi, niin haluaisin tietää millainen, jotta voin etsiä virheen. 

Sinulla oli hyviä kommentteja ja ehdotuksia; pyrin toteuttamaan niitä mahdollisuuksien mukaan! Kiitos!

**Comment by hanrastic** [comment]
Olisin voinut olla selkeämpi. Kyseessä oli siis vaan inputin validoimattomuuden auheuttama virhe. Eli avaimia ei oltu luotu ja kirjoitin vaan jotain tekstiä inputiksi.

**Comment by sonjamadetoja** [comment]
Kiitos tarkennuksesta!
