### ISSUE TITLE
Vertaisarviointi_1

### ISSUE THREAD

**Issue by nikolaipaukkonen** [sonjamadetoja/RSA-salaus#2]
Projekti ladattu 12.4.2022 klo 21:44

Yleisesti ottaen ohjelma näyttää toimivan tarkoituksenmukaisesti ja oikein ainakin pienillä syötteillä. Virheelliset syötteet (esim. kirjainten syöttäminen kokonaisluvuiksi tarkoitettuihin syötteisiin) aiheuttaa virheen, mutta tällaiset pienet virheenkäsittelyasiat eivät liene akuutteja tässä vaiheessa. Käytettävyyden kannalta voisi olla hyvä, että luodut avaimet jäisivät jollakin tavalla ohjelman muistiin, sillä niiden toistuva kopiointi ja liittäminen on hankalaa. Myös jonkinlainen export/import-vaihtoehto voisi olla paikallaan, joskaan ei liity ohjelman ydintoimintaan. 

Pidempien viestien kohdalla ohjelma kaatuu purkuvaiheessa. RSA:ssa käytössä olevan avaimen koko vaikuttaa kerralla salattavan viestin maksimipituuteen, joten ongelma on ratkaistava muulla tavoin (itselleni tuli vastaan esimerkiksi tällainen stackoverflow-ketju aiheesta: https://stackoverflow.com/questions/5866129/rsa-encryption-problem-size-of-payload-data). Tämä varmasti aukeaa paremmin mikäli päätät jatkaa paddingin toteuttamista – itsellänikin se on vasta edessä (teen siis työtä samasta aiheesta).  

Koodi on selkeästi kirjoitettua ja kommentoitu asianmukaisesti. Rakennetta voisi selkeyttää entisestään se, että sovelluslogiikkaan ja käyttöliittymään liittyvät osat siirrettäisiin omiin alikansioihinsa, mikä ei tosin näin pienessä ohjelmassa ole välttämätöntä. Alkulukujen tarkistusta voisi nopeuttaa ajamalla ensin yksinkertaisemman testin esimerkiksi käyttämällä muutaman sadan ensimmäisen alkuluvun listaa (jotka voi generoida vaikka Erastothenen seulalla tai sitten kovakoodata suoraan mukaan). Näin Rabin-Milleriä ei tarvitsisi ottaa heti käyttöön jokaisen tarkistettavan luvun kohdalla. 

Myös yksikkötestaus on toteutettu helposti seurattavalla tavalla ja kattaa tärkeimmät asiat. Suorituskyvyn testaaminen ajoittamalla esimerkiksi eri kokoisten avainten luomista tai purkuoperaatioita on varmasti mielenkiintoista jatkossa.

**Comment by sonjamadetoja** [comment]
Kiitos!
