### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by rundtjan** [sonjamadetoja/RSA-salaus#3]
Hienoa ja selkeää koodia, ja sovelluksen asennus, käyttö ja testaaminen sujui hyvin omalla koneella. Testikattavuus puskettu korkeaksi ja sain itse pylint-pisteiksi 9,68, mikä on varmasti vaatinut jonkin verran näplyttämistä ja kärsivällisyyttä!

Parannusehdotuksia ei hirveästi ole, nyt tässä vaiheessa kun ei lähdetä toteuttamaan uusi kokonaisuuksia (muuten olisin maininnut, että jotain padding-menetelmää voisi olla mielenkiintoisaa kokeilla salausvaiheessa). Järjestelmä voisi mahdollisesti herjaa virhettä, jos syöttää vialliset RSA-avaimet.

Hyvää dokumentaatiota, nopeasti sai selkeän kuvan, että mitä koodi tekee mitä (oli totta kai aika tuttuja algoritmejä kun itse tehnyt RSA:ta, mutta kuitenkin).

**Comment by sonjamadetoja** [comment]
Kiitos hyvistä kommenteista!
